### ISSUE TITLE
reference Audio can not be defined for abx-tests

### ISSUE THREAD

**Issue by nise** [HSU-ANT/beaqlejs#12]

**Comment by nise** [comment]
In the config file the A and B option can be defined, but the reference audio as stated in the mushra-test is missing.

**Comment by timobaumann** [comment]
see [Wikipedia on abx-tests](https://de.wikipedia.org/wiki/ABX-Test): ```Die Testperson hat Zugang zu drei Audioquellen: A, B und X. X wird zufällig gewählt und entspricht entweder A oder B. ```

**Comment by seebk** [comment]
Indeed, as Timo said, that's how a ABX test is usally defined. The reference is chosen randomly from A or B. If you want another behaviour you can simply copy the ABX test implementation and modify it to fit your needs.
