### ISSUE TITLE
submission of the results not possible

### ISSUE THREAD

**Issue by nise** [HSU-ANT/beaqlejs#13]
The submit button is not displayed.

The php script is not able to write a file in a writable folder that is owned by www-data.

All in all the beaqle seems to be not usable for production.

**Comment by nise** [comment]
time stamps are not collected

**Comment by timobaumann** [comment]
it appears that you are reporting multiple issues in one.

**Comment by seebk** [comment]
> All in all the beaqle seems to be not usable for production.

All in all it seems you are not posting any meaningful and did not read the documentation. If you are interested in a solution please post a complete bug report or question with all details such that I can understand what the problem actually is. I can tell you that many people have used BeaqleJS to collect submission results on a server and it works. It might not be plug'n'play to setup, but when you carefuly follow the instructions from the README it should work.

**Comment by nise** [comment]
Sorry for providing multiple issues that are all related to the submission process. In the mean time I found my way with a node.js backend. See https://github.com/nise/beaqle-node

**Comment by nise** [comment]
Because you provide a php backend service, it should be set as default in the config. Thus, the 3rd step of the setup instruction will become obsolete. 

Right now its written in the setup instructions that the path could be something like `http://yourdomain.com/mysubfolder/beaqleJS_Service.php.`. When using ajax that service should provided from the same origin. Otherwise some you will run into problem with Same Origin Policies.

**Comment by nise** [comment]
I woul suggest to reopen the issue

**Comment by seebk** [comment]
>Because you provide a php backend service, it should be set as default in the config. Thus, the 3rd step of the setup instruction will become obsolete. 

I see, yes it could be pre-configured to point to the PHP file in case you simply upload the whole BeaqleJS folder structure to your server.  I always assumed that people manually create a distribution package out of the project folder before upload , so they have to adjust the paths anyway. But seems this is not the case and so it makes sense to change this.

> Right now its written in the setup instructions that the path could be something like `http://yourdomain.com/mysubfolder/beaqleJS_Service.php.`. When using ajax that service should provided from the same origin. Otherwise some you will run into problem with Same Origin Policies.

Good point, I will add an info to the docs that one has to take care of this.

**Comment by seebk** [comment]
> See a screenshot of the missing submit button here: https://owncloud.pi6.fernuni-hagen.de/index.php/s/U2WvrVKuDFIDrBe

Again, I just downloaded the latest master branch, setup a docker webserver as described in the docks, configured online submission and did not experience any problems.  Can you provide steps how to reproduce the problem?

**Comment by seebk** [comment]
Ok, finally I got it... should be fixed in master now.
