### ISSUE TITLE
AudioContext cannot be created without first registering a user action on the page

### ISSUE THREAD

**Issue by alastair** [HSU-ANT/beaqlejs#16]
As of Chrome 71, you can no longer automatically create and start an AudioContext without the user having first performed an action on the page (to prevent annoying autoplay scripts, https://goo.gl/7K7WLu)
This means that when the AudioPool is created (https://github.com/HSU-ANT/beaqlejs/blob/6eccc5389379f260db5536c2fd0fe3d513406fac/js/beaqle.js#L434) the AudioContext is loaded in a paused state.

I have a patch for this that I've made in our version that moves the AudioPool creation into a separate function that I call when the Start! button is clicked. This makes the setup of a test a bit more complex (you need to create the Test, then on click call `initAudio`, and then call `startTests`)

I realise that this could be made a bit simpler by just calling `waContext.resume()` as the first step in the `startTests` method, but this means that a warning will always appear in the console of chrome notifying of this issue.

Do you prefer a patch that results in no warning, or one that requires the least amount of setup?

**Comment by alastair** [comment]
Here are the two possibilities: 

* separate initAudio: https://github.com/MTG/beaqlejs/commit/faeda2976ad7088d05c673272cd2c0a9d71b61f4
* force resume: https://github.com/MTG/beaqlejs/commit/0e309afcca917c4139a40f3408aedbd67f0074ac

Feel free to merge/cherry pick either of these branches (or ask me to make a PR!)

**Comment by seebk** [comment]
Thanks for reporting and investigating the issue. I decided to fix it with the initAudio() method but removed the checkBrowserFeatures() call as I prefer to be able to show the footer already on page load. This still shows a warning in the console. If there would be another method to test for WebAudioAPI support we could also get rid of this warning, but I could not find anything...

**Comment by alastair** [comment]
Thanks for the quick fix!
