### ISSUE TITLE
Strange audio artifacts on Chrome

### ISSUE THREAD

**Issue by jfsantos** [HSU-ANT/beaqlejs#4]
Using Google Chrome version 60.0.3112.101, if I make a long test with a lot of files, eventually all files start looping in a weird way and having a lot of noise and/or artifacts. Could this be related to how beaqlejs processes the audio files for looping?

**Comment by seebk** [comment]
Well that's really difficult to answer, could be anything. I never experienced what you described, but that does not mean that there is no bug in BeaqleJS. Can you reproduce this strange behaviour?

**Comment by jfsantos** [comment]
I ended up discovering those issues were due to hosting my data on Heroku. I moved the data to Amazon S3 and did not have this issue anymore. It might be due to differences on how Firefox and Chrome stream audio, but it's definitely not beaqlejs's fault! I'll close this issue now.
