### ISSUE TITLE
Mushra default rate setting

### ISSUE THREAD

**Issue by mariejo-j** [HSU-ANT/beaqlejs#8]
I'm helping a student set up a Mushra test and would first like to thank you for a very nice and clean script.  The student wants a scale be set at 50 by default. So in the config file I set this to:
"RateDefaultValue": 50,
But it remained at 0 on the test.
Looking at the beaqle.js file on line 1117 I saw this line and found that if I changed it from 0 to 50, it worked.
   $(this).slider('option', 'value', 50);

'tho being no programmer, I'm aware it's a crude way to do it. Which would be the correct way?

**Comment by seebk** [comment]
Thanks for your report and sorry for the late reply. Indeed, you spotted a bug and using `"RateDefaultValue": 50` in the config should have done the job. The bug is now fixed in the current Git master branch.

Your workaround is perfectly fine if you want to continue working with the last release.
